### PR TITLE
specifications: Add GT910 datasheet

### PR DESCRIPTION
**Pull request by cakehonolulu**

### CODE REVIEW

**Comment by hadess** [comment]
Perfect, thanks!

**Comment by cakehonolulu** [comment]
Hello!
I was wondering if I could help adding GT910 support on top of your goodix driver, since the ones that are found on several Linux Sources seem to have trouble doing i2c-related stuff on recovery mode.
Thanks for your help and for reading!
Have a nice day!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hadess** [comment]
The driver in this repository might not be updated, you'll want to start off the upstream kernel version. All the development work needs to happen on the linux-input@ kernel mailing-list.

**Comment by hadess** [comment]
Getting the 910 datasheet translated might be a good first pass, then try to compare it with 911 datasheet.

The differences are probably fairly minimal, and can probably be slotted in to the existing per-device branches.

**Pull request merged**
